# Read in the file
with open('ZL3b-n_CHANGED.txt', 'r') as file:
  filedata = file.read()

# Replace the target string
filedata_output = (
    filedata
        .replace('@128;', '€') # May not be in transliteration
        .replace('@130;', '‚')
        .replace('@131;', 'ƒ')
        .replace('@132;', '„')
        .replace('@133;', '…')
        .replace('@134;', '†')
        .replace('@135;', '‡')
        .replace('@136;', 'ˆ')
        .replace('@137;', '‰')
        .replace('@138;', 'Š')
        .replace('@139;', '‹')
        .replace('@140;', 'Œ')
        .replace('@142;', 'Ž')
        .replace('@145;', "‘")
        .replace('@146;', "’")
        .replace('@147;', '“')
        .replace('@148;', '”')
        .replace('@149;', '•')
        .replace('@150;', '–')
        .replace('@151;', '—')
        .replace('@152;', '˜') # Not Assigned
        .replace('@153;', '™')
        .replace('@154;', 'š')
        .replace('@155;', '›')
        .replace('@156;', 'œ')
        .replace('@158;', 'ž')
        .replace('@159;', 'Ÿ')
        .replace('@160;', ' ')
        .replace('@161;', '¡')
        .replace('@162;', '¢')
        .replace('@163;', '£')
        .replace('@164;', '¤')
        .replace('@165;', '¥')
        .replace('@166;', '¦')
        .replace('@167;', '§') # Omitted in GC's original table. It is used in the transliteration file.
        .replace('@168;', '¨')
        .replace('@169;', '©')
        .replace('@170;', 'ª')
        .replace('@171;', '«')
        .replace('@172;', '¬') # Do not appear in the transliteration file
        .replace('@173;', '­')
        .replace('@174;', '®')
        .replace('@175;', '¯')
        .replace('@176;', '°')
        .replace('@177;', '±')
        .replace('@178;', '²')
        .replace('@179;', '³')
        .replace('@180;', '´')
        .replace('@181;', 'μ')
        .replace('@182;', '¶') # Do not appear in the transliteration file
        .replace('@183;', '·')
        .replace('@184;', '¸')
        .replace('@185;', '¹')
        .replace('@186;', 'º')
        .replace('@187;', '»')
        .replace('@188;', '¼')
        .replace('@189;', '½')
        .replace('@190;', '¾')
        .replace('@191;', '¿')
        .replace('@192;', 'À')
        .replace('@193;', 'Á')
        .replace('@194;', 'Â')
        .replace('@195;', 'Ã') # Do not appear in the transliteration file
        .replace('@196;', 'Ä')
        .replace('@197;', 'Å')
        .replace('@198;', 'Æ')
        .replace('@199;', 'Ç')
        .replace('@200;', 'È')
        .replace('@201;', 'É')
        .replace('@202;', 'Ê')
        .replace('@203;', 'Ë')
        .replace('@204;', 'Ì')
        .replace('@205;', 'Í')
        .replace('@206;', 'Î')
        .replace('@207;', 'Ï')
        .replace('@208;', 'Ð')
        .replace('@209;', 'Ñ')
        .replace('@210;', 'Ò')
        .replace('@211;', 'Ó')
        .replace('@212;', 'Ô')
        .replace('@213;', 'Õ')
        .replace('@214;', 'Ö')
        .replace('@215;', '×')
        .replace('@216;', 'Ø') # Do not appear in the transliteration file
        .replace('@217;', 'Ù')
        .replace('@218;', 'Ú')
        .replace('@219;', 'Û')
        .replace('@220;', 'Ü')
        .replace('@221;', 'Ý') # Added in 2025
        .replace('@222;', 'Þ') # Added in 2025
        .replace('@223;', 'ß') # Added in 2025
        .replace('@224;', 'à')
        .replace('@225;', 'á')
        .replace('@226;', 'â')
        .replace('@227;', 'ã')
        .replace('@228;', 'ä')
        .replace('@229;', 'å')
        .replace('@230;', 'æ')
        .replace('@231;', 'ç')
        .replace('@232;', 'è')
        .replace('@233;', 'é')
        .replace('@234;', 'ê')
        .replace('@235;', 'ë')
        .replace('@236;', 'ì')
        .replace('@237;', 'í')
        .replace('@238;', 'î')
        .replace('@239;', 'ï')
        .replace('@240;', 'ð')
        .replace('@241;', 'ñ')
        .replace('@242;', 'ò')
        .replace('@243;', 'ó')
        .replace('@244;', 'ô')
        .replace('@245;', 'õ')
        .replace('@246;', 'ö')
        .replace('@252;', 'ü')
        .replace('@253;', 'ý')
        .replace('@254;', 'þ')
        .replace('@255;', 'ÿ')
)

# Write the file out again
with open('ZL3b-n_CHANGED.txt', 'w', encoding='utf-8') as file:
  file.write(filedata_output)