# Read in the file
with open('../transliterationFiles/ZL3b-n/ZL3b-n_CHANGED.txt', 'r') as file:
  filedata = file.read()

# Replace the target string
filedata_output = (
    filedata
        .replace('€') # May not be in transliteration
        .replace('‚')
        .replace('ƒ')
        .replace('„')
        .replace('…')
        .replace('†')
        .replace('‡')
        .replace('ˆ')
        .replace('‰')
        .replace('Š')
        .replace('‹')
        .replace('Œ')
        .replace('Ž')
        .replace("‘")
        .replace("’")
        .replace('“')
        .replace('”')
        .replace('•')
        .replace('–')
        .replace('—')
        .replace('˜') # Not Assigned
        .replace('™')
        .replace('š')
        .replace('›')
        .replace('œ')
        .replace('ž')
        .replace('Ÿ')
        .replace(' ')
        .replace('¡')
        .replace('¢')
        .replace('£')
        .replace('¤')
        .replace('¥')
        .replace('¦')
        .replace('§') # Omitted in GC's original table. It is used in the transliteration file.
        .replace('¨')
        .replace('©')
        .replace('ª')
        .replace('«')
        .replace('¬') # Do not appear in the transliteration file
        .replace('­')
        .replace('®')
        .replace('¯')
        .replace('°')
        .replace('±')
        .replace('²')
        .replace('³')
        .replace('´')
        .replace('μ')
        .replace('¶') # Do not appear in the transliteration file
        .replace('·')
        .replace('¸')
        .replace('¹')
        .replace('º')
        .replace('»')
        .replace('¼')
        .replace('½')
        .replace('¾')
        .replace('¿')
        .replace('À')
        .replace('Á')
        .replace('Â')
        .replace('Ã') # Do not appear in the transliteration file
        .replace('Ä')
        .replace('Å')
        .replace('Æ')
        .replace('Ç')
        .replace('È')
        .replace('É')
        .replace('Ê')
        .replace('Ë')
        .replace('Ì')
        .replace('Í')
        .replace('Î')
        .replace('Ï')
        .replace('Ð')
        .replace('Ñ')
        .replace('Ò')
        .replace('Ó')
        .replace('Ô')
        .replace('Õ')
        .replace('Ö')
        .replace('×')
        .replace('Ø') # Do not appear in the transliteration file
        .replace('Ù')
        .replace('Ú')
        .replace('Û')
        .replace('Ü')
        .replace('Ý') # Added in 2025
        .replace('Þ') # Added in 2025
        .replace('ß') # Added in 2025
        .replace('à')
        .replace('á')
        .replace('â')
        .replace('ã')
        .replace('ä')
        .replace('å')
        .replace('æ')
        .replace('ç')
        .replace('è')
        .replace('é')
        .replace('ê')
        .replace('ë')
        .replace('ì')
        .replace('í')
        .replace('î')
        .replace('ï')
        .replace('ð')
        .replace('ñ')
        .replace('ò')
        .replace('ó')
        .replace('ô')
        .replace('õ')
        .replace('ö')
        .replace('ü')
        .replace('ý')
        .replace('þ')
        .replace('ÿ')
)

# Write the file out again
with open('../transliterationFiles/ZL3b-n/ZL3b-n_CHANGED.txt', 'w', encoding='utf-8') as file:
  file.write(filedata_output)